### ISSUE TITLE
Can OGG be made embeddable?

### ISSUE THREAD

**Issue by erikd** [erikd/libsndfile#105]
@ DavidGriffith found that reading and writing OGG files within other files is not currently supported.

See if its possible to support this.

**Comment by DavidGriffith** [comment]
I only tried to read OGGV data.  I didn't try to write.

**Comment by evpobr** [comment]
@DavidGriffith :

> It turns out that my problem with playing an OGG embedded in a Blorb file is due to a bug/deficiency/oversight in libsndfile. Libsndfile cannot currently do that.
See erikd/libsndfile#105

It's not libsndfile bug. You're just doing it wrong.

Blorb is very specific game format, some kind of archive, which can contain both audio, and images, and even code. There is no sense to support reading from all the game archives, the libsndfile's purpose is audio encoding\decoding.

So you should write the code to work with blorb file yourself. Read Ogg data from Blorb to memory and use libsndfile virtual I\O API to decode it. That's the way how other games read audio data from theirs archives.

**Comment by erikd** [comment]
> It's not libsndfile bug. You're just doing it wrong.

I don't totally agree. libsndfile can read some other file formats (eg WAV, AIFF, AU) embedded in a larger file (see `tests/multi_file_test.c`). Ogg is currently not supported but I do not currently know of any reason why it could not be.

**Comment by evpobr** [comment]
Didn't even know that feature exists. Agreed, it should be implemented.

**Comment by erikd** [comment]
This is *extremely* unlikely to be in 1.0.29.

**Comment by evpobr** [comment]
Ok. I just wanted to fix that first after CMake reworking.

**Comment by erikd** [comment]
I'm pretty sure this is a rather difficult issue to fix. There are many much easier ones.

**Comment by DavidGriffith** [comment]
What, precisely, makes this problem difficult to fix?

**Comment by erikd** [comment]
I suspect it can't be made embeddable but I have not confirmed this.

The Ogg container format is designed for streaming. Unlike WAV/AIFF etc, there is no header component that can tell you how long the file is. That makes it kind of difficult to jump to the second file if the first file is an Ogg file.

**Comment by DavidGriffith** [comment]
That shouldn't be a problem if the container file format is designed sensibly, that is, length is written into metadata in the container.  I have no problems at all playing various OGGV chunks in a Blorb file when feeding the file pointer directly to libvorbis. If OGGV had this limitation, I'm sure it would have been noticed when the Blorb standard was written.

**Comment by erikd** [comment]
For compressed file formats,  have the length in samples written to the metadata is of little use, because it still doesn't tell you the length of the container. Furthermore, unless the assumption that the length is written to the metadata *always* true, it cannot be relied on.

**Comment by arthurt** [comment]
Might have been fixed inadvertently by #457. Need to test again.

**Comment by DavidGriffith** [comment]
> Might have been fixed inadvertently by #457. Need to test again.

I just tried it and I still get told `embedding not supported for this file format`.
