### ISSUE TITLE
Calling sf_open on this file puts sf_open() into an infinite loop (100% CPU usage, never returns)

### ISSUE THREAD

**Issue by jfriesne** [erikd/libsndfile#340]
Bug's context information:
- Mac Mini, 2.5GHz Intel Core i5, 8GB RAM
- MacOS/X 10.13.1
- libsndfile 1.0.28 (compiled locally using "./configure; make; make check"); make check had no errors
- Compiler:  Apple LLVM version 9.0.0 (clang-900.0.37)  (from Xcode version 9.0 (9A235))

To reproduce the fault:

1. Under MacOS/X (I'm on 10.13.1, in case the exact version matters), download and un-tar this file:

       https://public.msli.com/lcs/jaf/this_file_kills_sf_open_in_libsndfile_1.0.28.doc.tar

2. Run sndfile-info (from a libsndfile 1.0.28 build) on the resulting .doc file:
       sndfile-info ./this_file_kills_sf_open_in_libsndfile_1.0.28.doc

3. Note that sndfile-info never returns; instead it spins the CPU at 100% forever:

----

$ sndfile-info ./this_file_kills_sf_open_in_libsndfile_1.0.28.doc
[... nothing ever gets printed...]

If I do a "Sample Process" of the sndfile-info process while it is spinning, I get the results shown in this file:

    https://public.msli.com/lcs/jaf/sample-of-spinning-sndfile-info.txt

This appears to be a regression in the SD2/resource-fork-reading code of sf_open().  If I run sndfile-info from libsndfile v1.0.25, the following expected behavior is seen instead:

---
$ sndfile-info ./this_file_kills_sf_open_in_libsndfile_1.0.28.doc

Version : libsndfile-1.0.25

Error : Not able to open input file ./this_file_kills_sf_open_in_libsndfile_1.0.28.doc.
File : ./this_file_kills_sf_open_in_libsndfile_1.0.28.doc
Length : 23552

File contains data in an unknown format.

**Comment by evpobr** [comment]
Under Windows i've got the same error message as above, no hangs.

**Comment by jfriesne** [comment]
I suspect the bug is MacOS/X-specific, since it occurs in the function that reads the resource fork of a .sd2 file (which I suspect is an operation that libsndfile doesn't attempt under Windows).

**Comment by evpobr** [comment]
@erikd implemented that code, may be he could help. But he is very buzy. If you can help it whould be great, i don't have Mac and @erikd as i know. Some debugging or `git bisect` to find something to start from.

**Comment by jfriesne** [comment]
I don't know that I'm the best person to fix the bug, but I gave it a quick try anyway -- I replaced the following line of code (at line 526 of sd2.c):

                rsrc_id = read_rsrc_short (rsrc, rsrc->item_offset + k * 12) ;

with the following code block:

                // jaf's proposed modification -- exit the loop if we've reached an out-of-bounds offset
                int id_offset = rsrc->item_offset + k * 12;
                if (id_offset < 0 || id_offset + 1 >= rsrc->rsrc_len)
                { psf_log_printf (psf, "Exiting parser on id_offset of %d.\n", id_offset) ;
                        break ;
                        }
                rsrc_id = read_rsrc_short (rsrc, id_offset);

... and that seems to avoid the spinloop-issue, at least on my machine (see the new sndfile-info output, below).  Whether this is the "right way" to do it or not, I don't know.

Jeremys-Mac-mini:libsndfile lcsuser1$ ./programs/sndfile-info ~/this_file_kills_sf_open_in_libsndfile_1.0.28.doc
Error : Not able to open input file /Users/lcsuser1/this_file_kills_sf_open_in_libsndfile_1.0.28.doc.
File : /Users/lcsuser1/this_file_kills_sf_open_in_libsndfile_1.0.28.doc
Length : 23552
Resource fork : /Users/lcsuser1/this_file_kills_sf_open_in_libsndfile_1.0.28.doc/..namedfork/rsrc
Resource length : 326 (0x0146)
  data offset : 0x0100
  map  offset : 0x0114
  data length : 0x0014
  map  length : 0x0032
Finding parameters :
  Offset    RsrcId    dlen    slen    Value
  0x0100     49123       16      15    'Jeremy Friesner'
Exiting parser on id_offset of 326.
Found Parameters :
  sample-size : 0
  sample-rate : 0
  channels    : 0
Bad sample size (0)

Error : bad sample size.

**Comment by erikd** [comment]
Can you attach the file that causes this please?

**Comment by jfriesne** [comment]
Hi Erik,

I can when I get back to my computer, but that won’t be until Monday night.  If you want it attached sooner than that, you can download it from the link I provided and attach it.

Jeremy

**Comment by erikd** [comment]
Ah, missed the link. With git HEAD:
```
> ./programs/sndfile-play this_file_kills_sf_open_in_libsndfile_1.0.28.doc
Playing this_file_kills_sf_open_in_libsndfile_1.0.28.doc
Error : bad data offset.
```
I get the same result when I check out the 1.0.28 git tag.

**Comment by erikd** [comment]
This gets recognized as an SD2 file, which may have a resource fork. Without the resource fork, its not possible to trigger this on any OS other than OSX.

**Comment by erikd** [comment]
Cannot reproduce this issue:
```
> ls -l this_file_kills_sf_open_in_libsndfile_1.0.28.doc ._this_file_kills_sf_open_in_libsndfile_1.0.28.doc 
-rw-r----- 1 erikd erikd   881 Nov 23  2017 ._this_file_kills_sf_open_in_libsndfile_1.0.28.doc
-rw-r----- 1 erikd erikd 23552 Nov 23  2017 this_file_kills_sf_open_in_libsndfile_1.0.28.doc
 
> ./programs/sndfile-info this_file_kills_sf_open_in_libsndfile_1.0.28.doc
Error : Not able to open input file this_file_kills_sf_open_in_libsndfile_1.0.28.doc.
File : this_file_kills_sf_open_in_libsndfile_1.0.28.doc
Length : 23552
Resource fork : ._this_file_kills_sf_open_in_libsndfile_1.0.28.doc
Resource length : 881 (0x0371)
Trying offset of 0x52 bytes.
  data offset : 0x41A6
  map  offset : 0x54520052
  data length : 0x0000
  map  length : 0x22B0000
Error : rsrc.data_offset (16806, 0x41A6) > len

Error : bad data offset.
```

**Comment by evpobr** [comment]
@jfriesne , was your issue fixed in v1.0.29 release?

**Comment by jfriesne** [comment]
@evpobr I just downloaded and compiled the v1.0.29 release on my Mac (OS/X 10.15.6) and tried it and I see that the bug is still present.   sndfile-info still spins the CPU at 100% forever, without printing any output.

I also verified that if I apply the change to sd2.c that is posted in my Nov 22, 2017 edit above, and then recompile v1.0.29, the spin loop does not occur and instead I get the following output:

```
Jeremys-Mac-mini-2:libsndfile-1.0.29 jaf$ ./programs/sndfile-info ~/Downloads/this_file_kills_sf_open_in_libsndfile_1.0.28.doc
Error : Not able to open input file /Users/jaf/Downloads/this_file_kills_sf_open_in_libsndfile_1.0.28.doc.
File : /Users/jaf/Downloads/this_file_kills_sf_open_in_libsndfile_1.0.28.doc
Length : 23552
Resource fork : /Users/jaf/Downloads/this_file_kills_sf_open_in_libsndfile_1.0.28.doc/..namedfork/rsrc
Resource length : 326 (0x0146)
  data offset : 0x0100
  map  offset : 0x0114
  data length : 0x0014
  map  length : 0x0032
Finding parameters :
  Offset    RsrcId    dlen    slen    Value
  0x0100     49123       16      15    'Jeremy Friesner'
Exiting parser on id_offset of 326.
Found Parameters :
  sample-size : 0
  sample-rate : 0
  channels    : 0
Bad sample size (0)

Error : bad sample size.
```

<img width="1030" alt="PastedGraphic-1" src="https://user-images.githubusercontent.com/1404232/91302618-9b31e500-e75b-11ea-8f0d-10dc8b6a9cfc.png">

**Comment by evpobr** [comment]
@jfriesne , how about pull request?

**Comment by jfriesne** [comment]
@evpobr When I try to push my branch to the GitHub repository, I get a "permission denied" error:

$ git push --set-upstream origin jaf/#340-sf_open-infinite-loop-on-doc-file
remote: Permission to erikd/libsndfile.git denied to jfriesne.
fatal: unable to access 'https://github.com/erikd/libsndfile.git/': The requested URL returned error: 403

**Comment by jfriesne** [comment]
Github won't let me push my branch:

```
$ git push --set-upstream origin jaf/#340-sf_open-infinite-loop-on-doc-file
ERROR: Permission to erikd/libsndfile.git denied to jfriesne.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by evpobr** [comment]
I think you need to [fork a repo](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo).
